### ISSUE TITLE
build doesn't verify commit mesages

### ISSUE THREAD

**Issue by ggascoigne** [Tripwire/octagon#316] opened 2018-10-10 21:54 UTC
The build should use commitlint to enforce commit message format.  That would stop commit such as this one https://github.com/Tripwire/octagon/commit/b26c0c4ceda02094cad66ef8f10fdfe4a18941f7 from failing to trigger a release.

See the expertOps project for an example.

**Comment by youngbob** [comment] 2018-12-14 21:03
Duplicate of #223

**Closed by youngbob** 2018-12-14 21:03 UTC
